### ISSUE TITLE
ADMIN: enable GH discussions

### ISSUE THREAD

**Issue by icegood** [SELinuxProject/selinux-notebook#17]
could you please add 'Discussions' page for forum on both book and selinux projects?

**Comment by bachradsusi** [comment]
-1 for enabling Discussion in SELinuxProject/selinux . The main communication channel is selinux@vger.kernel.org - https://lore.kernel.org/selinux - and I think that another (official?) web oriented channel where it's possible to discuss things would make them less discoverable.

**Comment by icegood** [comment]
ok, tnx

**Comment by pcmoore** [comment]
I agree with everything @bachradsusi said.  While I understand the GH "Discussions" mechanism to be very nice, we already have a communication channel in place (the email list) and duplicating and/or fracturing that would be a mistake.
