### ISSUE TITLE
Q: looking for documentation on the reference policy

### ISSUE THREAD

**Issue by freedom1b2830** [SELinuxProject/selinux-notebook#19]
I want to write a library to read such rules.
You can provide a detailed example of rules (te if fc) with all sorts of syntax:

```
optional_policy(`
    dbus_system_bus_client(kde_t)
    dbus_connect_system_bus(kde_t)
')
optional_policy(`
    gen_require(`
        type user_t;
        role user_r;
    ')
    kde_run(user_t, user_r)
')
```
with monolithic syntax:
```
require {
         type discord_t;
         class lnk_file read;
}
```
With deprecated macros.

With obsolete keywords

```
dominance { role message_filter_r { role unconfined_r };}
```
Complete example for MLS MCS

And other things

**Comment by pcmoore** [comment]
Hi @freedom1b2830, the [Reference Policy](https://github.com/SELinuxProject/selinux-notebook/blob/main/src/reference_policy.md) section is likely the closest you will get outside the sources themselves:

* https://github.com/SELinuxProject/refpolicy
