### ISSUE TITLE
BUG: rendered book contains local filesystem references

### ISSUE THREAD

**Issue by bachradsusi** [SELinuxProject/selinux-notebook#30]
1. Download https://github.com/SELinuxProject/selinux-notebook/releases/download/20221216/SELinux_Notebook.pdf
2. Look for CIL Reference Guide

Same for epub:

```
<li><a href="file:///home/pcmoore/sources/selinux-notebook/src/notebook-examples/selinux-policy/cil/CIL_Reference_Guide.pdf">CIL Reference Guide</a></li>
```

**Comment by pcmoore** [comment]
I don't know what your problem is @bachradsusi, it works fine on *my* system ;)

Thanks for pointing this out, if you have time to work on a fix it would be greatly appreciated, otherwise I'll add it to my todo list.

**Comment by pcmoore** [comment]
Fixed via https://github.com/SELinuxProject/selinux-notebook/pull/34.
