### ISSUE TITLE
Q: new release request

### ISSUE THREAD

**Issue by d1nuc0m** [SELinuxProject/selinux-notebook#31]
Since 20221216 there have been [a few commits](https://github.com/SELinuxProject/selinux-notebook/compare/7eba84c76a68e8f284f5a33d3f0cd298655b6cbe..e87fe613ee9e1a4c6921555e548f9d93bd3184cc), maybe it would be interesting to have a new release

**Comment by pcmoore** [comment]
Hi @d1nuc0m,

Yes, that probably would be a good idea, although it would be nice if we could fix issue #30 first.

**Comment by pcmoore** [comment]
Tada!

* https://github.com/SELinuxProject/selinux-notebook/releases/tag/20240430
