### ISSUE TITLE
BUG: `make epub` fails

### ISSUE THREAD

**Issue by parided** [SELinuxProject/selinux-notebook#32]
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/brillo-device/Makefile' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/cil/CIL_Reference_Guide.pdf' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/network/README.md' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/kernel/kern-nb-policy.txt' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/reference-policy/modules.conf' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/README.md' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/android-10/Makefile' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/brillo/Makefile' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/sepgsql/testdb-example.sql' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/tools/build-sepolicy.md' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/sepgsql/README.md' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/reference-policy/build.conf' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/android-4/Makefile' not found
Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/cil/cil-nb-policy.txt' not found
Referenced file '/usr/share/doc/selinux-policy/html/index.html' not found
34% Transcodifica di un ebook in corso...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'EPUB/toc.ncx' from manifest
Creating AZW3 Output...
67% AZW3 Output plugin in esecuzione
Serializing resources...
Splitting markup on page breaks and flow limits, if any...
	Split into 3 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
	Split into 2 parts
Creating KF8 output
	Generating KF8 markup...
Tag table has no aid and a too large chunk size. Adding anyway.

**Comment by dburgener** [comment]
"make epub" works fine on my system.  We need to understand the difference on your system.

This looks like it may only be the error portion of the output.  Can you paste the whole output so I can see how far in the build it got successfully?

Is this running on a clean repository on the HEAD of main?

**Comment by pcmoore** [comment]
Hi @parided,

It looks like @dburgener responded while I was typing my own response, but `make epub` also works on my system and the last time it ran as part of the GH actions it also ran successfully.  In addition to the suggestions already made by @dburgener, can you share the version of `ebook-convert` that you are using?

For example, on my system I am running ebook-convert/calibre v7.9.0:
```
% ebook-convert --version
ebook-convert (calibre 7.9.0)
Created by: Kovid Goyal <somebody@example.com>
```

**Comment by pcmoore** [comment]
Without any follow-up from the original reporter I'm going to close this issue, @parided if you're able to provide more info about the failures please feel free to re-open.

**Comment by mcoronadojess-ogg** [comment]
> Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/brillo-device/Makefile' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/cil/CIL_Reference_Guide.pdf' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/network/README.md' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/kernel/kern-nb-policy.txt' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/reference-policy/modules.conf' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/README.md' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/android-10/Makefile' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/brillo/Makefile' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/sepgsql/testdb-example.sql' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/tools/build-sepolicy.md' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/sepgsql/README.md' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/reference-policy/build.conf' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/embedded-policy/android-policy/android-4/Makefile' not found Referenced file 'EPUB/text/file%3a/home/paride/git/selinux-notebook/src/notebook-examples/selinux-policy/cil/cil-nb-policy.txt' not found Referenced file '/usr/share/doc/selinux-policy/html/index.html' not found 34% Transcodifica di un ebook in corso... Merging user specified metadata... Detecting structure... Flattening CSS and remapping font sizes... Source base font size is 12.00000pt Removing fake margins... Cleaning up manifest... Trimming unused files from manifest... Trimming 'EPUB/toc.ncx' from manifest Creating AZW3 Output... 67% AZW3 Output plugin in esecuzione Serializing resources... Splitting markup on page breaks and flow limits, if any... Split into 3 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Split into 2 parts Creating KF8 output Generating KF8 markup... Tag table has no aid and a too large chunk size. Adding anyway.

Endinan
